apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true

    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      username: analytics_user
      defaultDatabase: analytics
      dialTimeout: 10
      queryTimeout: 60
      validateSql: true

    secureJsonData:
      password: analytics_pass